id: P000532
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-16 15:44:58.575062
source_metadata:
  id: bdr:W8LS19192
  title: རྒྱུད་བཞིའི་འགྲེལ་བ་མེས་པོའི་ཞལ་ལུང་། སྨད་ཆ།
  author: ''
  volumes:
    f8832814d8ca485ebf82c7674daade09:
      image_group_id: I8LS19194
      title: Volume 1 of /rgyud bzhi'i 'grel ba mes po'i zhal lung / smad cha/
      volume_number: 1
      total_pages: 1108
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
