id: I0151EE9C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:44:42+00:00'
last_modified: '2022-06-07T12:08:37.897679+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19192
  title: རྒྱུད་བཞིའི་འགྲེལ་བ་མེས་པོའི་ཞལ་ལུང་། སྨད་ཆ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AB79:
      image_group_id: I8LS19194
      title: Volume 1 of /rgyud bzhi'i 'grel ba mes po'i zhal lung / smad cha/
      total_pages: 1108
      order: 1
      base_file: AB79.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
